### ISSUE TITLE
Coverage reporting incorrect results with buidler

### ISSUE THREAD

**Issue by justinjmoses** [sc-forks/solidity-coverage#491] opened 2020-04-06 18:25 UTC
Using solidity-coverage with buidler from a repo that also uses truffle results in reports that seem to be missing key parts. 

If you run `npm run test:coverage` from [this synthetix branch - please ignore the codecov report](https://github.com/Synthetixio/synthetix/pull/492), you'll see the following output:

![image](https://user-images.githubusercontent.com/799038/78590592-111acb80-7810-11ea-98ee-6ad6d9128bdf.png)

Now the reports here cover tests ported over to `test/unit` so the results will be different to `npm run coverage`, however the above results are missing a number of the key solidity files tested by `test/unit/*` - `AddressResolver.sol` for one, `SuplySchedule.sol` for another.

> Note: to allow instrumented contracts to be deployed, setting `gasLimit` on `providerOptions` in `.solcover.js` didn't work, @maxsam4 worked out that it was needed in `builder.config.js` under 			`networks.buidlerevm.blockGasLimit`: `0x1fffffffffffff`, - which is odd as solidity-coverage uses ganache under the hood I believe? cc @alcuadrado

> Note: the `ExchangeRates` contract is still failing to be deployed, not sure why. Removing this test spec however doesn't change the coverage results.

**Comment by cgewecke** [comment] 2020-04-06 18:42
@justinjmoses Have left a note in the Synthetix PR about resolving this by defining a coverage network in `buidler.config.js`

There seems to be a bug here when overriding BuidlerEVM as a network though....

**Comment by cgewecke** [comment] 2020-06-11 00:21
Unfortunately have not been able to reproduce this with latest buidler. Have updated the docs to recommend that people define a coverage network for the time being.

Closing, will re-open if someone pings with more info.

**Closed by cgewecke** 2020-06-11 00:21 UTC
Labels: bug
