### ISSUE TITLE
Coverage results in error `Transaction reverted: function call to a non-contract account`

### ISSUE THREAD

**Issue by TeamAtBigeyes** [sc-forks/solidity-coverage#727] opened 2022-06-28 11:11 UTC
Despite the fact that running `yarn test` works, when running `yarn coverage` command on repo https://github.com/BigEyes-Space/big-eyes-token, solidity coverage results in the following error:

```bash
  Uniswap router contract
    1) Should be able to add liquidity to uniswap contract
    After liquidity supply
      A second user should be able to:
        2) "before each" hook for "swap exact ETH for tokens"


  35 passing (20s)
  2 failing

  1) Uniswap router contract
       Should be able to add liquidity to uniswap contract:
     Error: Transaction reverted: function call to a non-contract account
    at UniswapV2Router02.getReserves (@uniswap/v2-periphery/contracts/libraries/UniswapV2Library.sol:31)
    at UniswapV2Router02._addLiquidity (@uniswap/v2-periphery/contracts/UniswapV2Router02.sol:45)
    at UniswapV2Router02.addLiquidity (@uniswap/v2-periphery/contracts/UniswapV2Router02.sol:71)
    at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
    at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
    at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
    at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)


  2) Uniswap router contract
       After liquidity supply
         "before each" hook for "swap exact ETH for tokens":
     Error: Transaction reverted: function call to a non-contract account
    at UniswapV2Router02.getReserves (@uniswap/v2-periphery/contracts/libraries/UniswapV2Library.sol:31)
    at UniswapV2Router02._addLiquidity (@uniswap/v2-periphery/contracts/UniswapV2Router02.sol:45)
    at UniswapV2Router02.addLiquidity (@uniswap/v2-periphery/contracts/UniswapV2Router02.sol:71)
    at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
    at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
    at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
    at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)




-------------------------------|----------|----------|----------|----------|----------------|
File                           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------|----------|----------|----------|----------|----------------|
 contracts/                    |    54.06 |    35.48 |    59.62 |    54.04 |                |
  BigEyes.sol                  |      100 |      100 |      100 |      100 |                |
  BigEyesNFT.sol               |       75 |      100 |    66.67 |       75 |          45,54 |
  BigEyesNFTs.sol              |    89.29 |       50 |       75 |    89.29 |       46,47,61 |
  BurnableReflectionERC20.sol  |      100 |      100 |      100 |      100 |                |
  Bytes32Utils.sol             |    91.67 |       50 |      100 |    91.67 |              8 |
  CalculateAmountOutMin.sol    |    57.14 |      100 |    55.56 |    57.14 |... 43,44,48,49 |
  ERC20Metadata.sol            |       50 |      100 |       25 |       50 |       19,23,27 |
  NativeTokenReceiver.sol      |      100 |       50 |      100 |      100 |                |
  OwnershipByAccessControl.sol |      100 |      100 |      100 |      100 |                |
  PaymentSplitter.sol          |    47.54 |    23.33 |       55 |    46.77 |... 232,241,258 |
  ReflectionERC20.sol          |     45.1 |     37.5 |     52.5 |    45.32 |... 433,564,568 |
  RoundDiv.sol                 |      100 |      100 |      100 |      100 |                |
  Swapping.sol                 |    16.67 |      100 |       25 |    14.29 |... 14,20,21,25 |
  TokenRecover.sol             |      100 |      100 |      100 |      100 |                |
 contracts/Imports/            |      100 |      100 |      100 |      100 |                |
  ImportStrings.sol            |      100 |      100 |      100 |      100 |                |
  ImportUniswapFactory.sol     |      100 |      100 |      100 |      100 |                |
  ImportUniswapLibrary.sol     |      100 |      100 |      100 |      100 |                |
  ImportUniswapRouter.sol      |      100 |      100 |      100 |      100 |                |
 contracts/StringsLib/         |    27.34 |     22.5 |    28.57 |    27.88 |                |
  MemoryLib.sol                |    51.85 |    66.67 |       60 |    54.05 |... 58,59,61,62 |
  StringsLib.sol               |    21.43 |    14.71 |    11.11 |    20.31 |... 228,229,232 |
 contracts/interfaces/         |      100 |      100 |      100 |      100 |                |
  IRewardDistributor.sol       |      100 |      100 |      100 |      100 |                |
-------------------------------|----------|----------|----------|----------|----------------|
All files                      |    46.57 |    32.32 |    55.93 |     45.8 |                |
-------------------------------|----------|----------|----------|----------|----------------|

> Istanbul reports written to ./coverage/ and ./coverage.json
Error in plugin solidity-coverage: ❌ 2 test(s) failed under coverage.
```

this abnormal functionality can also be observed in [Github Actions run](https://github.com/BigEyes-Space/big-eyes-token/runs/7091145921?check_suite_focus=true).

**Comment by aWoWed** [comment] 2022-10-07 10:16
I think, that you have anot changed the UniswapV2Library keccak hash.

But i have almost the same error, but i have changed pair-hash. It occurs only, when running `hardhat coverage`
![image](https://user-images.githubusercontent.com/76687755/194531193-e2171592-6522-49b1-8874-dc77b3c3d7f4.png)

**Comment by aWoWed** [comment] 2022-10-07 18:06
The problem is connected with the LACK OF solidity optimizer in coverage. COZ bytecode in `hardhat coverage` and `hardhat test` have different length

**Comment by cgewecke** [comment] 2024-01-26 05:33
Closing, looks like the comment above explains the issue.

**Closed by cgewecke** 2024-01-26 05:33 UTC
