### ISSUE TITLE
Send / Transfer fails with 'invalid opcode' if destination fallback function instrumented.

### ISSUE THREAD

**Issue by lewisbarber** [sc-forks/solidity-coverage#106] opened 2017-09-10 20:12 UTC
So I've tried everything in the FAQ, but I'm still getting 'invalid opcode' error messages when trying to call the _sendTransaction_ method of web3. Any idea why this might be happening?

When running the tests using only truffle it works... Perhaps I'm missing something?

**Comment by cgewecke** [comment] 2017-09-10 20:20
@lewisbarber If you could share a link to the code that's producing this error (or generate a minimal truffle project example that produces it) I'll happily take a look at it.

**Comment by lewisbarber** [comment] 2017-09-10 20:35
Hey @cgewecke, thanks!

https://github.com/sharpe-capital/sharpe-token/tree/feature/presale-bounties

This branch produces the problem:

_truffle test_ - everything works
_npm run coverage_ - nothing works!

**Comment by cgewecke** [comment] 2017-09-10 21:41
@lewisbarber Thanks, I'm getting these errors on the coverage run.  
![sharpe-coverage](https://user-images.githubusercontent.com/7332026/30253219-7c6d12f4-9635-11e7-89c1-0fa482b9652b.png)

Is that what you're seeing as well?

When I run the regular tests: `npm test` (or `truffle test` ) I see:

![sharpe-gas](https://user-images.githubusercontent.com/7332026/30253135-c1943544-9633-11e7-9e16-cc471d58f16b.png)

Using Node 7.10.0, on OSX. 

Could you verify you're getting a clean run on your end? Or advise re: getting everything to pass so there's a baseline to compare to?

**Comment by lewisbarber** [comment] 2017-09-10 21:43
So your problem with _truffle test_ is you need to run testrpc with more gas/block (so it's more like the live network - our code does quite a bit)... The command is:

_testrpc -a 10 -l 4000000000_

The first error you show for the coverage is the same as what I see.

**Comment by cgewecke** [comment] 2017-09-11 00:58
@lewisbarber Thanks for reporting this. 

The problem is with the `transfer` [here](https://github.com/sharpe-capital/sharpe-token/blob/feature/presale-bounties/contracts/Presale.sol#L385). It's gas constrained by design and because the MultiSigWallet's fallback function is getting instrumented with some expensive events the call maxes out. 

Tests will pass if you exclude the MultiSigWallet from the instrumentation process by adding the following to `.solcover.js`:
```
skipFiles: ['lib/MultiSigWallet.sol']
```
Don't know if you have a pressing audit coming up or something but that Wallet's been combed over pretty carefully so leaving it out might not matter much.

Renaming your issue to reflect the underlying problem.

**Comment by lewisbarber** [comment] 2017-09-11 07:02
Ah - that makes perfect sense. I think it's acceptable for us to exclude the MultiSigWallet from the coverage report. In fact, we should probably exclude all third-party libs.

Thanks for taking a look at this so quickly, it's great to have such an important library properly supported! :)

**Comment by area** [comment] 2017-09-11 13:13
Add this to the growing list of reasons to motivate us to move to the `debug_tracetransaction` approach!

**Comment by cgewecke** [comment] 2017-09-11 13:57
@area +1.

Think I will try modifying the call / transfer stipends in `opFns.js` and also do #92 (testrpc upgrade) today - hopefully that will fix this for the short term. . .

**Comment by cgewecke** [comment] 2017-09-13 18:03
Closing via #108. Published with `0.2.3`.

**Comment by cgewecke** [comment] 2017-10-02 19:20
@lewisbarber Just a heads up - we're reverting our fix for this. I don't think that will affect you since you were going to exclude all 3rd party code in the `skipFiles`....

Re-opening. This will continue to happen for the time being.

**Closed** 2019-07-14 00:19 UTC
Labels: V2, bug

**Comment by BrendanChou** [comment] 2019-07-17 21:17
@cgewecke is this supposed to be fixed now? I'm confused about why I'm still seeing errors for it

**Comment by cgewecke** [comment] 2019-07-17 21:33
@BrendanChou Yes it looks like it's fixed on `0.6.2` (testrpc-sc v6.4.5-sc.3). If you're still seeing it with `0.6.2` could you link to a repro when you have a chance? 

We have a passing unit test for that case [here](https://github.com/sc-forks/solidity-coverage/blob/master/test/app.js#L344-L361). Its relevant solidity source and js test are here:
+ [Wallet.sol](https://github.com/sc-forks/solidity-coverage/blob/master/test/sources/cli/Wallet.sol)
+ [wallet.js](https://github.com/sc-forks/solidity-coverage/blob/master/test/cli/wallet.js)

**Comment by BrendanChou** [comment] 2019-07-17 23:06
Awesome, 0.6.2 fixed it, thank you!
