### ISSUE TITLE
Support "pragma experimental"

### ISSUE THREAD

**Issue by HaleTom** [sc-forks/solidity-coverage#128] opened 2017-10-05 12:40 UTC
The [Solidity 0.4.17 release notes](https://github.com/ethereum/solidity/releases) say:

> As we are getting closer to the next breaking release, we want to give everyone a heads up by introducing pragma experimental "v0.5.0" which already enables some of the new safety features of the 0.5.0 release.

Currently I get:
```
There was a problem instrumenting ./coverageEnv/contracts/ProofOfExistence1.sol: SyntaxError: Expected "solidity", comment, end of line, or whitespace but "e" found. Line: 2, Column: 8
Exiting without generating coverage...
```

Where line 2 is:
```
pragma experimental "v0.5.0";
```

**Comment by cgewecke** [comment] 2017-10-05 14:10
Thanks for reporting. This is caused by a failure in the parser dependency. 

@HaleTom  out of curiosity when you run regular `truffle test` on a  `pragma experimental "v0.5.0"` does it compile without error? They look like they're currently pinned to `solc 0.4.15` and I though the experimental feature was released in `0.4.16`.

**Comment by HaleTom** [comment] 2017-10-06 10:37
It seems like it's a `truffle` issue.

* [Upgrade solc to v0.4.17 #605](https://github.com/trufflesuite/truffle/issues/605)

* [Look into using `solc`'s parser instead of `solidity-parser`, so we can stay up to date with language features. #502](https://github.com/trufflesuite/truffle/issues/605) <-- prevents manually changing to 0.4.17.

My output with *only* `solc 0.4.17` installed:
```
$ truffle test
Using network 'development'.

SyntaxError: Expected "solidity", comment, end of line, or whitespace but "e" found.
    at peg$buildStructuredError (/usr/lib/node_modules/truffle/build/cli.bundled.js:181971:12)
    at Object.peg$parse [as parse] (/usr/lib/node_modules/truffle/build/cli.bundled.js:185570:11)
    at Object.parse (/usr/lib/node_modules/truffle/build/cli.bundled.js:83782:23)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:59136:36
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:49114:5
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:60660:16
    at next (/usr/lib/node_modules/truffle/build/cli.bundled.js:69109:18)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:49099:7
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:96498:5
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:69014:16
```

**Comment by elenadimitrova** [comment] 2017-10-10 09:09
Let's reopen this as `truffle` 4 beta includes solc 0.4.17 update. It's back to being a `solidity-coverage` issue.

**Comment by cgewecke** [comment] 2017-10-10 14:09
@area self-assigning and will try to fix parser today unless you're already working on this.  This and #131 also need:
+ bump dev dep to truffle 4 beta
+ a simple test that uses the new language features

**Comment by area** [comment] 2017-10-10 16:44
Nope, I've not started on this yet, so you should go for it

**Comment by cgewecke** [comment] 2017-10-10 17:33
@area Oh, no worries!

**Comment by cgewecke** [comment] 2017-10-11 20:28
Published: `0.2.6`

**Comment by elenadimitrova** [comment] 2017-10-12 11:23
I'm still getting the same error with `0.2.6` :/

**Comment by cgewecke** [comment] 2017-10-12 13:24
@elenadimitrova  [this](https://github.com/sc-forks/solidity-coverage/blob/2ecbe5efc6fad113e66e69efdd9e915a8aed5024/test/sources/cli/PureView.sol) is the test that was put in to verify the grammar fix. Is that correct?

It compiles and runs on the truffle beta in CI.

**Comment by elenadimitrova** [comment] 2017-10-12 13:51
@cgewecke 
I use
```
pragma solidity ^0.4.17;
pragma experimental "v0.5.0";
pragma experimental "ABIEncoderV2";
```
But I tried with just what's in the test and still compile fails.. I've triple checked the SC version.

**Comment by cgewecke** [comment] 2017-10-12 15:38
@elenadimitrova Sorry, could you look in the output of `npm install` and verify that sc's `solidity-parser` is at this commit `8f3e126`?

Are you on yarn?

**Comment by elenadimitrova** [comment] 2017-10-12 18:20
@cgewecke  I'm on yarn, yes. Output below but not that commit
![screen shot 2017-10-12 at 21 20 10](https://user-images.githubusercontent.com/703848/31512331-2b9a4b90-af93-11e7-892e-9e8a9ccfb27f.png)

**Comment by cgewecke** [comment] 2017-10-12 18:23
Ok cool - I'll put our parser on npm. . .that will probably fix it.

**Comment by cgewecke** [comment] 2017-10-12 22:58
Hopefully fixed now.

**Closed by cgewecke** 2017-10-12 22:58 UTC

**Comment by elenadimitrova** [comment] 2017-10-13 09:50
Yes, thank you! 🎉
