### ISSUE TITLE
In coverage network some tests failed but when i run `truffle test` all tests passed

### ISSUE THREAD

**Issue by borysyuk** [sc-forks/solidity-coverage#285] opened 2018-09-03 15:41 UTC
[solidity-coverage.log](https://github.com/sc-forks/solidity-coverage/files/2346079/solidity-coverage.log)
I have test project on solidity. There are a few contracts and libraries. Some of my tests failed when i run your utility. When i "skip" some tests -  i got failed in other contract. But all tests passed when i run `truffle test` or `truffle develop` than `test`.
You can download my code here: https://github.com/borysyuk/consensys-project-simple-market-place

I have attached log from my console when i run `$ ./node_modules/.bin/solidity-coverage`

**Comment by cgewecke** [comment] 2018-09-03 19:04
Hi @borysyuk. There are a couple of weird things Truffle is doing that interfere with the way coverage rewrites the contract artifact ABIs in your case.  Apologies for this. They're fixable...
+ Remove `test/sol`. Truffle's test command automatically recompiles any solidity contracts imported into Solidity tests files, undoing all the work the coverage tool did prior to the test run. Solidity-coverage can't support solidity testing at the moment. 
+ In [ProductCatalog.sol](https://github.com/borysyuk/consensys-project-simple-market-place/blob/master/contracts/libraries/ProductCatalog.sol#L6) and [ShopCatalog.sol](https://github.com/borysyuk/consensys-project-simple-market-place/blob/master/contracts/libraries/ShopCatalog.sol) rewrite the import path for List.sol to be explicitly relative, eg:
```solidity
import "contracts/libraries/List.sol"; // From this
import "./List.sol"; // To this
```
Truffle's also recompiling those for some reason - that's an issue I didn't know existed until just now. 

(Nice job with your tests btw).

![screen shot 2018-09-03 at 12 01 52 pm](https://user-images.githubusercontent.com/7332026/44999342-4a72c180-af71-11e8-9928-8d149de0baa1.png)

**Comment by borysyuk** [comment] 2018-09-04 09:15
@cgewecke Thanks for the help! One question: It is possible to skip test/sol in config file or do something to avoid that problem? I don't want to remove it because there is one important test.

**Comment by cgewecke** [comment] 2018-09-04 15:50
@borysyuk Unfortunately no. The problem is caused by behavior at Truffle that we can't change or really work around. Is there a way of representing the same test in JS?

**Comment by borysyuk** [comment] 2018-09-05 15:51
@cgewecke At this time, i don't know how. Contract which i have tested in `test/sol` is a library with external functions. I have tried to create js test to test it. I have create mock contract to test library so as result, i test mock contract instead library. But truffle has some strange behavior, it raise error when it try `deploy` mock contract which uses library with external calls for testing.

**Comment by cgewecke** [comment] 2019-07-12 22:25
Closing, this has been open for a while and describes a known limitation of solidity-coverage that we don't have an immediate fix for.

**Closed by cgewecke** 2019-07-12 22:25 UTC
