### ISSUE TITLE
Should cache instrumented contracts

### ISSUE THREAD

**Issue by Fang-** [sc-forks/solidity-coverage#244] opened 2018-06-14 22:23 UTC
Currently, every run of solidity-coverage re-instruments the contracts, even if those haven't changed. Would it be possible to cache the instrumented contracts, and only recreate those if the corresponding source contract has changed?

**Comment by cgewecke** [comment] 2018-06-15 17:21
Hi @Fang.  At the moment we copy the entire target into a temp folder, rewrite the contracts, run the tests and throw everything away. The more I think about how we would cache the more complicated it seems tbh. Truffle has some hardwired behavior and configurability deficits that don't really work in our favor here. 

About how long is a coverage run taking for you? What proportion of the time is spent in the two compilation sweeps vs. instrumenting?

**Comment by Fang-** [comment] 2018-06-15 17:28
Initial compile is ~13 seconds. It then spends nearly three minutes instrumenting, and another ~18 seconds to compile again afterwards. So, instrumenting is definitely the majority of the time here.

I naively figured you could just store an md5 hash of the source files alongside the instrumented versions, and only re-instrument if the source file no longer matches the appropriate hash. But there's probably more I'm not taking into consideration then.

**Comment by cgewecke** [comment] 2018-06-15 18:45
Oh . . . 3 min is appalling. Can you share your `.solcover.js`? 

I think you should only see times like that if you're using the `copyNodeModules` option. In most cases you should be able to get more normal performance by using the `copyPackages` option to only specify Solidity packages you've installed with npm. The way Truffle has historically resolved solidity imports doesn't search recursively outside the project root the way it should. But everything else you `require` can be found normally - e.g it doesn't need to added to the temporary folder. Ex:
```javascript
module.exports = {
  copyPackages: ['zeppelin-solidity']
}
```

The hash idea is a good one - I'm a little concerned about maintaining a cache in someone's project since SC is installed as a local dev dependency. Another issue is that Truffle profiles the build artifacts folder by comparing file modification times and automatically decides what to compile. . . it's a little tricky but yes I think your suggestion is right.

**Comment by Fang-** [comment] 2018-06-15 18:52
Yes, I already read about `copyPackages`. My `.solcover.js` looks like this:

```
module.exports = {
    copyPackages: ['zeppelin-solidity'],
    skipFiles: [ 'irrelevant/',
                 'irrelevant.sol' ]
};
```

> I'm a little concerned about maintaining a cache in someone's project

You already produce a `coverage/` output folder, it might make sense to put it in there. But that's ultimately up to you.

**Comment by cgewecke** [comment] 2018-06-15 18:56
Ah smart! Ok you win. I don't understand how the instrumentation can be taking that long. Like zeppelin is 107 contracts and it's nowhere near that.

**Comment by cgewecke** [comment] 2018-06-15 19:00
Idk actually, let me check that out....

**Comment by Fang-** [comment] 2018-06-15 19:02
[Some](https://github.com/urbit/constitution/blob/master/contracts/Ships.sol) of our [contracts](https://github.com/urbit/constitution/blob/master/contracts/Constitution.sol) are kinda big? But nothing absurd, and it's only like 11 contracts in total.

Thanks for your consideration!

**Comment by cgewecke** [comment] 2018-06-15 19:08
Yes cool let me look! I just ran Zeppelin and everything went in ~10 sec. The compilation is the big time sink for them. Just pinged you on gitter.

**Comment by cgewecke** [comment] 2018-06-15 19:41
@Fang Agreed. It's surprisingly bad. . . confirmed that it's 3 min and seems like Ships and Constitution are the taking quite while.

**Comment by cgewecke** [comment] 2019-07-12 07:29
Instrumentation is much faster now. Much much much faster. Closing, but please ping if you disagree.

**Closed by cgewecke** 2019-07-12 07:29 UTC
