### ISSUE TITLE
Solcover giving binary (10 results on OpenST-Protocol repo.

### ISSUE THREAD

**Issue by noslav** [sc-forks/solidity-coverage#266] opened 2018-07-31 09:54 UTC
Ran solcover with the following packages on - `develop` of  `https://github.com/OpenSTFoundation/openst-protocol.git` 
  
* name: openst-protocol,
  version: 0.9.1,
  description: ,
  devDependencies: {
    abi-decoder: 1.0.9,
    assert: 1.4.1,
    bignumber.js: 4.1.0,
    ganache-cli: 6.1.0,
    keccak: 1.4.0,
    rlp: 2.1.0,
    solidity-coverage: ^0.5.5,
    solparse: 2.2.5,
    truffle: 4.1.8,
    web3: 1.0.0-beta.33
  author: OpenST Foundation Ltd.,
  license: Apache v2.0

**Comment by cgewecke** [comment] 2018-07-31 19:46
Duplicate of #267

**Closed by cgewecke** 2018-07-31 19:46 UTC
