### ISSUE TITLE
Permission denied error for testrpc-sc (OSX only)

### ISSUE THREAD

**Issue by thackerronak** [sc-forks/solidity-coverage#240] opened 2018-05-30 10:18 UTC
command
```
./node_modules/.bin/solidity-coverage
```
error 
```
{ Error: Command failed: /Users/smartSense/Ronak Thacker/Node JS/TLPICOWalletApp1/contracts/node_modules/ethereumjs-testrpc-sc/build/cli.node.js --accounts 35 --port 8555 --gasLimit 17592186044415
/bin/sh: /Users/smartSense/Ronak: Permission denied

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
  killed: false,
  code: 126,
  signal: null,
  cmd: '/Users/smartSense/Ronak Thacker/Node JS/TLPICOWalletApp1/contracts/node_modules/ethereumjs-testrpc-sc/build/cli.node.js --accounts 35 --port 8555 --gasLimit 17592186044415' }
testRpc stderr:
/bin/sh: /Users/smartSense/Ronak: Permission denied

Cleaning up...
Shutting down testrpc-sc (pid 3034)
testRpc errored after launching as a childprocess.
Exiting without generating coverage...
```

Tested in OSX and facing error.

**Comment by cgewecke** [comment] 2018-06-03 18:45
@thackerronak I can't reproduce this. 

`testrpc-sc` creates a file and writes to it - it's possible there's something about the way your node permissions are configured that's causing a problem here.

**Comment by cgewecke** [comment] 2018-06-07 05:01
Closing, please ping if you're still having trouble with this.

**Comment by victorvanderhulst** [comment] 2018-06-28 19:58
I have exactly the same issue. Is there a solution found?

**Comment by cgewecke** [comment] 2018-06-28 20:07
@victorvanderhulst How are you installing?

**Comment by victorvanderhulst** [comment] 2018-06-30 04:45
@cgewecke By following the instructions in the Readme. 
I just run: 
`npm install --save-dev solidity-coverage`

Running ./node_modules/.bin/solidity-coverage results in:

```
testRpc stderr:
/bin/sh: /Users/victor/Projects/private_sale_SC_Lockup-Git/node_modules/ethereumjs-testrpc-sc/build/cli.node.js: Permission denied

```

**Comment by cgewecke** [comment] 2018-06-30 05:00
@victorvanderhulst You shouldn't have to do this but if you run
```
chmod +x /Users/victor/Projects/private_sale_SC_Lockup-Git/node_modules/ethereumjs-testrpc-sc/build/cli.node.js
```
does that work?

Are you also on OSX like @thackerronak?   

I'm on OSX and I don't get this error. There must some difference in the way our Node permissions are configured.

NB: we invoke that file directly because there have been issues for yarn users invoking the `.bin`.

**Comment by victorvanderhulst** [comment] 2018-06-30 07:55
@cgewecke Thanks, permission denied error is resolved ;)
And I could figure this out myself of course... too bad ;)

I'm using MacOS indeed.

**Comment by cgewecke** [comment] 2018-06-30 18:10
@victorvanderhulst Ok cool - I'm going to re-open this because it's weird and `chmod` should not be necessary.

**Comment by cgewecke** [comment] 2019-07-12 22:28
I think this is fixed. We're invoking testrpc-sc using `npx` and the permissions are inherited from ganache-cli. This might have been a weird bug I introduced at some point by messing around on our fork... If anyone else experiences this, please ping.
`0.6.0`

**Closed by cgewecke** 2019-07-12 22:28 UTC
