### ISSUE TITLE
Files not being skipped

### ISSUE THREAD

**Issue by WyseNynja** [sc-forks/solidity-coverage#312] opened 2019-01-07 03:12 UTC
I have an "external" directory full of contracts from other projects. I think that I do want these copied into coverageEnv, but I do not want/need coverage for them.

My .solcover.js:
```
module.exports = {
    copyPackages: ['openzeppelin-solidity'],
    deepSkip: true,
    port: 8555,
    skipFiles: ['../external'],
};
```

I've also tried with `skipFiles: ['external'],`

The docs say "Array of contracts or folders (with paths expressed relative to the contracts directory) that should be skipped when doing instrumentation."  ../external is relative to the contracts directory, but I don't think it's working.

While running `solidity-coverage`, it seems to still be scanning this directory:
```
$ solidity-coverage
Generating coverage environment
Running: truffle compile --network coverage 
(this can take a few seconds)...
Compiling ./contracts/privatestuff.sol...
Compiling openzeppelin-solidity/contracts/access/Roles.sol...
Compiling openzeppelin-solidity/contracts/access/roles/PauserRole.sol...
Compiling openzeppelin-solidity/contracts/access/roles/WhitelistAdminRole.sol...
Compiling openzeppelin-solidity/contracts/access/roles/WhitelistedRole.sol...
Compiling openzeppelin-solidity/contracts/lifecycle/Pausable.sol...
Compiling openzeppelin-solidity/contracts/math/Math.sol...
Compiling openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/IERC20.sol...
Compiling openzeppelin-solidity/contracts/utils/ReentrancyGuard.sol...
Writing artifacts to ./build/contracts

Instrumenting  ./coverageEnv/contracts/privatestuff.sol
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/extensions/contracts/Forwarder/MixinAssets.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/extensions/contracts/Forwarder/MixinExchangeWrapper.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/extensions/contracts/OrderMatcher/MixinAssets.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/extensions/contracts/OrderValidator/OrderValidator.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/protocol/contracts/protocol/AssetProxy/ERC20Proxy.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/protocol/contracts/protocol/AssetProxy/ERC721Proxy.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/protocol/contracts/protocol/AssetProxy/MultiAssetProxy.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/protocol/contracts/protocol/Exchange/MixinAssetProxyDispatcher.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
Warning: The file at ./coverageEnv/external/0x-monorepo/contracts/protocol/contracts/protocol/Exchange/MixinWrapperFunctions.sol was identified as a Solidity Contract, but did not parse correctly. You may ignore this warning if it is not a Solidity file, or your project does not use it
```

I realize the warning says it can be ignored, but it is spending too much time generating these warnings. If it didn't scan this directory at all it would be much faster.

I've tried with and without deepSkip: true.

**Comment by cgewecke** [comment] 2019-07-12 07:26
@WyseNynja Thanks, I think this is a duplicate of #283. Going to address this there. `0.6.0` instruments a couple orders of magnitude faster. You may see these warnings but they should just be annoying as noise rather than time wasted.

**Closed by cgewecke** 2019-07-12 07:26 UTC
