### ISSUE TITLE
Error in plugin solidity-coverage: TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by JimLynchCodes** [sc-forks/solidity-coverage#745] opened 2022-09-09 14:44 UTC
All my tests pass, but when I run "hardhat coverage" it just breaks with this error:

![Screen Shot 2022-09-09 at 10 44 49 AM](https://user-images.githubusercontent.com/5354163/189377352-890d16d7-a01d-4e7f-956b-8d5edfdde670.png)

**Comment by cgewecke** [comment] 2022-09-09 16:22
Duplicate of #622

**Closed by cgewecke** 2022-09-09 16:22 UTC

**Comment by JimLynchCodes** [comment] 2022-09-09 16:36
@celeduc  yeah, unfortunately that issue was closed with no response, let alone a real solution.

you should know- it was your issue! 😂

**Comment by JimLynchCodes** [comment] 2022-09-09 16:41
Are you saying the solution should be to add "--network hardhat" to the command even though that is the default?

Wow, would be a seriously bad bug in hardhat!!

Unfortunately, that causes a different error- tests that pass normally now all fail with this error: "Error: Transaction reverted: library was called directly"

![Screen Shot 2022-09-09 at 12 40 57 PM](https://user-images.githubusercontent.com/5354163/189399640-119a659c-ffc4-4e52-8bcf-6710d84758ff.png)

And since you prematurely closed my issue like a fckn ass hole I guess I should open a new one. 🤷‍♂️
