### ISSUE TITLE
`address` property of Function Type is not supported

### ISSUE THREAD

**Issue by ecp4224** [sc-forks/solidity-coverage#704] opened 2022-04-02 16:17 UTC
When using properties of a function type variable, the `address` property isn't recognized

Example 
```
pragma solidity ^0.8.0;

contract ATest {
    struct SavedCallbackFunction {
        function (uint256) external returns (bool) func;
    }

    mapping(bytes32 => SavedCallbackFunction[]) private listeners;

    function on(bytes32 eventId, function (uint256) external returns (bool) callback) external {
        listeners[eventId].push(SavedCallbackFunction(callback));
    }

    function _trigger(bytes32 eventId, uint256 data) internal {
        SavedCallbackFunction[] storage callbacks = listeners[eventId];

        for (uint i = 0; i < callbacks.length; i++) {
            bytes4 listenerFuncSelector = callbacks[i].func.selector;
            address listenerAddress = callbacks[i].func.address; //This line errors in solidity-coverage

            bytes memory cdata = abi.encodeWithSelector(listenerFuncSelector, data);

            (bool success, bytes memory result) = listenerAddress.delegatecall{gas: gasleft()}(cdata);

            require(success, string(result));
        }
    }
}
```

Error
```
> ATest.sol
> solidity-coverage cleaning up, shutting down ganache server
Error: Could not instrument: ATest.sol. (Please verify solc can compile this file without errors.) missing {'from', 'error', 'calldata', 'revert', 'callback', 'leave', 'payable', 'constructor', 'receive', Identifier} at 'address' (18:56)
    at Object.parse (/Users/eddiepenta/Projects/UniversalToken/node_modules/@solidity-parser/parser/src/parser.ts:81:11)
    at Instrumenter.instrument (/Users/eddiepenta/Projects/UniversalToken/node_modules/solidity-coverage/lib/instrumenter.js:74:30)
    at API.instrument (/Users/eddiepenta/Projects/UniversalToken/node_modules/solidity-coverage/lib/api.js:98:48)
    at plugin (/Users/eddiepenta/Projects/UniversalToken/node_modules/solidity-coverage/plugins/truffle.plugin.js:81:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.4.5 (core: 5.4.5)
Node v16.7.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
 
`solc` can compile this sample fine with no errors.

Tested on [0.8.0-beta.1](https://www.npmjs.com/package/solidity-coverage/v/0.8.0-beta.1)

**Comment by cgewecke** [comment] 2022-04-24 23:20
Hi, apologies for the delay responding and thank you for the reproduction steps. This looks like a problem that would need to be fixed in @solidityparser/solidity-parser's antlr grammar

I think having `address` as a built-in object property is a problem because that keyword is assumed to be an elementary type.

(Will cross post your issue to the antlr grammar repo and update this response with a link.)

**Comment by cgewecke** [comment] 2024-01-29 01:04
This was fixed at solidity-parser/parser

https://github.com/solidity-parser/antlr/issues/12#issuecomment-1290268494

**Closed by cgewecke** 2024-01-29 01:04 UTC
Labels: bug, Investigate
