### ISSUE TITLE
There was a problem instrumenting ./coverageEnv/contracts/****

### ISSUE THREAD

**Issue by fabianorodrigo** [sc-forks/solidity-coverage#358] opened 2019-07-25 01:25 UTC
I got the message "There was a problem instrumenting ./coverageEnv/contracts/..." in following projects. Hope it can be helpful.

https://github.com/golemfactory/golem-contracts 
Solc version: ^0.5.3 
Message: There was a problem instrumenting ./coverageEnv/contracts/GNTDeposit.sol: SyntaxError: Expected ")", ",", comment, end of line, or whitespace but "_" found. Line: 190, Column: 28

https://github.com/nicholashc/MerkleShip/truffle
Solc version:  ^0.5.0
Messag: There was a problem instrumenting ./coverageEnv/contracts/MerkleShip.sol: SyntaxError: Expected ";", comment, end of line, or whitespace but "p" found. Line: 57, Column: 21

https://github.com/maticnetwork/testnet-token-contracts
Solc version: 0.5.2
Message: There was a problem instrumenting ./coverageEnv/contracts/MaticTokenAirdrop.sol: SyntaxError: Expected ")", ",", comment, end of line, or whitespace but "_" found. Line: 17, Column: 45

https://github.com/dappisland/HedgeFund
Solc version:  ^0.5.7
Message: There was a problem instrumenting ./coverageEnv/contracts/HedgeFund.sol: SyntaxError: Expected ")", ",", comment, end of line, or whitespace but "u" found. Line: 168, Column: 41

https://github.com/hav-noms/final-project-hav-noms
Solc version:  ^0.5.0
Message: There was a problem instrumenting ./coverageEnv/contracts/EternalStorage.sol: SyntaxError: Expected ")", ",", comment, end of line, or whitespace but "v" found. Line: 43, Column: 61

https://github.com/METADIUM/MetaResolvers
Solc version:  ^0.5.0
Message: There was a problem instrumenting ./coverageEnv/contracts/examples/Resolvers/ERC1056/EthereumDIDRegistryInterface.sol: SyntaxError: Expected ")", ",", comment, end of line, or whitespace but "v" found. Line: 10, Column: 74

https://github.com/dev-bootcamp-2019/final-project-nicholashc/truffle
Solc version: ^0.5.0 
Message: There was a problem instrumenting ./coverageEnv/contracts/MerkleShip.sol: SyntaxError: Expected ";", comment, end of line, or whitespace but "p" found. Line: 57, Column: 21

https://github.com/Onther-Tech/minime
Solc version: ^0.5.0 
Message: There was a problem instrumenting ./coverageEnv/contracts/Controlled.sol: SyntaxError: Expected ";", "=", comment, end of line, or whitespace but "p" found. Line: 8, Column: 21

**Comment by cgewecke** [comment] 2019-07-25 01:29
@fabianorodrigo Which version of solidity-coverage are you using? Can you run:
```
npm list solidity-coverage
```

**Comment by cgewecke** [comment] 2019-07-25 02:16
@fabianorodrigo Going through these in order. . .I'm using Truffle v5.0.26 and solidity-coverage 0.6.3. I'm adding a coverage network to the truffle-config.js per the README instructions and at the command line running 
```
npx solidity-coverage
```
**Golem Output (with no additional configuration)**

![Screen Shot 2019-07-24 at 7 05 17 PM](https://user-images.githubusercontent.com/7332026/61840562-66f84080-ae46-11e9-8440-5ceb2e6b314a.png)

**Comment by cgewecke** [comment] 2019-07-25 02:17
**2. https://github.com/nicholashc/MerkleShip/truffle**

Bad link.

**Comment by cgewecke** [comment] 2019-07-25 02:23
**3. Matic Networks**

Not sure what's going on here but it instrumented fine. Seems to be missing a `.csv` file and would require some additional project specific configuration.  This project *also* has native solidity tests which are not supported, but they seem to have compiled ok.

![Screen Shot 2019-07-24 at 7 20 55 PM](https://user-images.githubusercontent.com/7332026/61841126-88f2c280-ae48-11e9-9728-6d27934be20a.png)

**Comment by cgewecke** [comment] 2019-07-25 02:27
@fabianorodrigo I can't reproduce these errors. It would be helpful if you provided clear reproduction steps for one project - e.g linked to a fork where you have installed coverage, which I can clone and run a command that results in the same error you're seeing

Closing.

**Closed by cgewecke** 2019-07-25 02:27 UTC

**Comment by fabianorodrigo** [comment] 2019-07-25 10:22
> @fabianorodrigo Which version of solidity-coverage are you using? Can you run:
> 
> ```
> npm list solidity-coverage
> ```

I'm using 0.6.3

**Comment by fabianorodrigo** [comment] 2019-07-25 10:41
@cgewecke, I'm sorry. I found out my mistake. A few weeks ago I cloned solidity-coverage and used 'npm link' in order to use it as dependency. So I wasn't actually running version 0.6.3. I'm going to repair this and report if I found something else.

**Comment by cgewecke** [comment] 2019-07-25 16:44
@fabianorodrigo Ah that makes sense! Thank you anyway for testing a wide array of projects, it's super helpful.  

> and report if I found something else

👍
