### ISSUE TITLE
Cannot find module 'scrypt-shim'

### ISSUE THREAD

**Issue by fabianorodrigo** [sc-forks/solidity-coverage#547] opened 2020-10-24 20:57 UTC
Hello,

I follow the guide to upgrading from 0.6.x to 0.7.x for this project https://github.com/bndes/bndestoken/tree/master/Back-Blockchain, but I receive the an error "Error: Cannot find module 'scrypt-shim'" when run truffle run coverage.

Regards,

**Comment by cgewecke** [comment] 2020-10-25 15:08
Hi @fabianorodrigo,

Could you list your Node version, solidity-coverage version, and OS?

I am able to install soliidty-coverage@latest locally on Node 10, 12, and 14 on Mac OSX without seeing this error.

**Comment by fabianorodrigo** [comment] 2020-10-26 14:00
Sure!

Truffle v5.1.23 (core: 5.1.23)
Solidity v0.5.16 (solc-js)
Node v10.15.3
Web3.js v1.2.1
solidity-coverage@0.7.11

**Comment by cgewecke** [comment] 2020-10-31 20:13
Hi @fabianorodrigo, just ran into this myself using Node 10 while installing a [Hegic fork][1] we use here for testing.

Was able to get installation to work by running `yarn` instead of `npm install`. 

Not sure what the problem is here...maybe some combination of outdated Node and npm...


[1]: https://github.com/sc-forks/contracts-v1

**Comment by cgewecke** [comment] 2020-12-22 20:30
Closing because Node LTS is 14 and this has a workaround.

**Closed by cgewecke** 2020-12-22 20:30 UTC
Labels: Node 10, has-workaround
